export const WINDOWSTATE = {
  NONE: "NONE",
  LOGIN: "LOGIN",
  CLOSE: "CLOSE",
  APPROVE: "APPROVE",
  THIRDPARTYSIGN: "THIRDPARTYSIGN",
};
export const STAKINGTYPE = {
  DELEGATE: 2,
  UNDELEGATE: 3,
  WITHDRAWREWARD: 4,
};
export const TRANSACTIONTYPE = {
  SEND: "SEND",
  DELEGATE: "DELEGATE",
  UNDELEGATE: "UNDELEGATE",
  WITHDRAWREWARD: "WITHDRAWREWARD",
};
export const TRANSACTIONCLASS = {
  TRANSACTION: "Transaction",
  STAKINGTRANSACTION: "StakingTransaction",
};

export const HARMONY_REQUEST_TYPE = "TO_ONEWALLET_EXTENSION";
export const HARMONY_RESPONSE_TYPE = "FROM_ONEWALLET_EXTENSION";
